FROM node:alpine AS node-frontend

# build arguments
ARG APP_KEY
ARG JWT_SECRET
ARG VITE_APP_NAME
ARG VITE_FRONTEND_URL
ARG VITE_API_URL_CLIENT
ARG VITE_API_URL_SERVER
ARG VITE_STRIPE_PUBLISHABLE_KEY
ARG LOG_CHANNEL
ARG QUEUE_CONNECTION
ARG MAIL_MAILER
ARG FILESYSTEM_PUBLIC_DISK
ARG FILESYSTEM_PRIVATE_DISK
ARG APP_NAME
ARG APP_URL
ARG APP_CDN_URL
ARG APP_FRONTEND_URL
ARG APP_SAAS_MODE_ENABLED
ARG APP_SAAS_STRIPE_APPLICATION_FEE_PERCENT
ARG DATABASE_URL

# Add environment variables to the build
ENV APP_KEY=$APP_KEY
ENV JWT_SECRET=$JWT_SECRET
ENV VITE_APP_NAME=$VITE_APP_NAME
ENV VITE_FRONTEND_URL=$VITE_FRONTEND_URL
ENV VITE_API_URL_CLIENT=$VITE_API_URL_CLIENT
ENV VITE_API_URL_SERVER=$VITE_API_URL_SERVER
ENV VITE_STRIPE_PUBLISHABLE_KEY=$VITE_STRIPE_PUBLISHABLE_KEY
ENV LOG_CHANNEL=$LOG_CHANNEL
ENV QUEUE_CONNECTION=$QUEUE_CONNECTION
ENV MAIL_MAILER=$MAIL_MAILER
ENV FILESYSTEM_PUBLIC_DISK=$FILESYSTEM_PUBLIC_DISK
ENV FILESYSTEM_PRIVATE_DISK=$FILESYSTEM_PRIVATE_DISK
ENV APP_NAME=$APP_NAME
ENV APP_URL=$APP_URL
ENV APP_CDN_URL=$APP_CDN_URL
ENV APP_FRONTEND_URL=$APP_FRONTEND_URL
ARG APP_SAAS_MODE_ENABLED=$APP_SAAS_MODE_ENABLED
ARG APP_SAAS_STRIPE_APPLICATION_FEE_PERCENT=$APP_SAAS_STRIPE_APPLICATION_FEE_PERCENT
ENV DATABASE_URL=$DATABASE_URL

WORKDIR /app/frontend

RUN apk add --no-cache yarn

COPY ./frontend/package.json ./frontend/yarn.lock ./

COPY ./frontend .

# yarn install and yarn build steps are separated because the container ran out of memory
# build:csr is used instead because of a problem in passing environment variables
# RUN yarn install && yarn build
RUN yarn install
RUN yarn build:csr

FROM serversideup/php:beta-8.3.2-fpm-alpine

ENV PHP_OPCACHE_ENABLE=1

RUN install-php-extensions intl

RUN apk add --no-cache nodejs yarn nginx supervisor

COPY --from=node-frontend /app/frontend /app/frontend

COPY ./backend /app/backend
RUN chown -R www-data:www-data /app/backend \
    && find /app/backend -type d -exec chmod 755 {} \; \
    && find /app/backend -type f -exec chmod 644 {} \; \
    && chmod -R 775 /app/backend/storage /app/backend/bootstrap/cache \
    && composer install --working-dir=/app/backend \
        --ignore-platform-reqs \
        --no-interaction \
        --no-dev \
        --optimize-autoloader \
        --prefer-dist \
    && chmod -R 775 /app/backend/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer

COPY ./docker/all-in-one/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/all-in-one/supervisor/supervisord.conf /etc/supervisord.conf

COPY ./docker/all-in-one/scripts/startup.sh /startup.sh
RUN dos2unix /startup.sh && chmod +x /startup.sh

EXPOSE 80

WORKDIR /app

CMD ["/startup.sh"]
